export const SEARCH_REQUEST_STATUS_CHANGE = 'SEARCH_REQUEST_STATUS_CHANGE';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const MANIFEST_REQUEST_STATUS_CHANGE = 'MANIFEST_REQUEST_STATUS_CHANGE';
export const RECENT_MANIFEST_REQUEST_STATUS_CHANGE = 'RECENT_MANIFEST_REQUEST_STATUS_CHANGE';
export const MANIFEST_UPLOAD_STATUS_CHANGE = 'MANIFEST_UPLOAD_STATUS_CHANGE';
