# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misirlou', '0010_auto_20160603_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='remote_url',
            field=models.TextField(unique=True),
        ),
    ]
