# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('misirlou', '0013_manifest_warnings'), ('misirlou', '0014_auto_20160606_1233'), ('misirlou', '0015_manifest_last_tested'), ('misirlou', '0016_auto_20160606_1316')]

    dependencies = [
        ('misirlou', '0012_manifest_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='_warnings',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='last_tested',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 6, 13, 1, 15, 295156)),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='error',
            new_name='_error',
        ),
    ]
