# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misirlou', '0013_manifest_warnings_squashed_0016_auto_20160606_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='last_tested',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
